var CACHE_PREFIX = GAME_NAME;
var login_name = '';
var say
var gamestarted = false;
var Game = null;
var thisapp = null;
var debug = false;
var reconnected = false;
var checkothermovesTO = null;
var top_anim_duration_fadein = 0.3;
var top_anim_duration_sustain = 2
var winlose_anim_delay = 5
var players_info = {}
var myplayerid = '';
var otherplayermodels = {}
var is_in_anim = false;
var gamestarted = false
var myturn = false;
var total_players = 1;
var playerOrder
var checkothermovesTO = null
var pionsqueue = null
var message_top = null


var boardview = null;
var hidewinlose = null;
var loopback = null;
var popperposition = [296,284];
var colororder = {0:'blue',1:'yellow',2:'green',3:'red'}
var colororder_inv = {'blue':0,'yellow':1,'green':2,'red':3}
var pionw = 42;
var pionh = 51;
var players_colors = {0:'blue',1:'blue',2:'blue',3:'blue'};
var colorchooser = null;
var playerlist_clickblock = false;
var pcols = {}
var currentTurn = '';
var currentTurn_original = '';
var pre_played = {};
var is_pre = 1;
var popitblock = true;
var eliminated = [];
var turnshowupdate_lock = 1;
var pre_winner = '';
var pre_winner_act ='';
var changeturnafterroll = false;
var secondstep=0;
var playerpionviews = {}
var playerByPionId = {}
var pionsMap = {}
var pionsMapByPionId = {}
var pionsMapGridCell = {}
var playerPaths = {}
var has_winning = 0;
var possible_moves = {}
var boardoffsetx = 180;
var boardoffsety = 3;
var startposReturnHome = 0;
var startposMoveAnim = 0;
var endposMoveAnim = 0;
var wtfblock = 0;
var speedreturnhome = 0.06;
var speedmove = 0.09;
var playasecondtime = 0;
var wontrophees = {}
var counttrophees = 0;
var totplayersremaining = 0;
var colora = {0:'#4da6ff',1:'#ffff4d',2:'#47d147',3:'#ff3c3c'}
var gameended = 0;
var unlockwrong=0
var oldzindex = 0

var pre_test = [4,5,2,4]
var pre_test_count = 0
/*var popper_audio = null
var place_audio = null
var win_audio = null
var wrong_audio = null
var losegame_audio = null
var ingoal_audio = null
var eat_audio = null
var backtohome_audio = null
var master_audio=null*/

