var CACHE_PREFIX = GAME_NAME;
var login_name = '';
var say
var beep_timeout = null;
var beep_timeout2 = null
var initGrid=false;
var initMini=false;
var endgamesent=false;
var gamestarted = false;
var Game = null;
var blockById = {}
var blockByIdOp = {}
var cellById = {}
var blockByCellId = {}
var cellByBlockId = {}
var spaceview = null;
var is_in_anim = false;
var is_in_anim_op = false;
var anims = {}
var animspeed = 0.2
var animspeedop = 0.15
var blocksToMove = []
var blocksToMoveOp = []
var thisapp = null;
var debug = false;
var colind = { 'b':'blue','y':'yellow','g':'green','w':'white','o':'orange','r':'red', 't':'trans' }
var posind = { 't':'top','b':'bottom','l':'left','r':'right' }
var currentSnap = { }
var lastSnap
var blocksToSend = {}
var touched = -1;
var blocksqueue = null
var max_anims = 8
var checkothermovesTO = null;
var offsetx = 40;
var offsety = 91;
var miniById = {}
var blockallinputs = false;
var otherplayerwon = false;
var playlosestarted = false;
var playwingamestarted = false;
var reconnected = false;
var dangeralreadyplayed = false;
var stopclickaudio = false;